
public enum Properties {
    ASSOCIATIVITY,
    COMMUTATIVITY,
    CLOSURE,
    LEFT_IDENTITY_LEFT_INVERSE,
    RIGHT_IDENTITY_LEFT_INVERSE,
    LEFT_IDENTITY_RIGHT_INVERSE,
    RIGHT_IDENTITY_RIGHT_INVERSE,
}
