
public enum Quantifier {
	    FOR_ALL_X_FOR_ALL_Y,
	    FOR_ALL_X_EXISTS_Y,
	    FOR_ALL_X_EXISTS_UNIQUE_Y,
	    EXISTS_X_FOR_ALL_Y,
	    EXISTS_X_EXISTS_Y,
	    EXISTS_X_EXISTS_UNIQUE_Y,
	    EXISTS_UNIQUE_X_FOR_ALL_Y,
	    EXISTS_UNIQUE_X_EXISTS_Y,
	    EXISTS_UNIQUE_X_EXISTS_UNIQUE_Y
}